name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit Test
        run: npm ci && npm test
   sonarcloud:
    name: Test de qualité
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
      # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=ludovicangenard
            -Dsonar.projectKey=ludovicAngenard_devops-CICD
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN:  ${{ secrets.SONAR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}